name: kbw
title: Ket Bitwise simulator
version: git
grade: devel
summary: The Ket Bitwise simulator
description: Source code available at https://gitlab.com/quantum-ket/kbw

base: core20
confinement: strict

parts:
  python:
    plugin: python
    python-packages: 
      - conan 
    stage-packages:
      - libpython3.8

  kbw:
    plugin: cmake
    source: .
    build-packages: 
      - pkg-config
      - uuid-dev
      - curl
      - make
      - default-jre
      - unzip
      - g++
      - gcc
    build-environment:
      - PATH : $PATH:/root/parts/python/install/bin
      - PYTHONPATH: /root/parts/python/install/lib/python3.8/site-packages
    cmake-parameters:
      - -DSNAP=1
    after:
      - python

apps:
  kbw:
    command: usr/bin/kbw
    plugs:
      - home
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

